spring.application.name=kienesis-consumer

aws.kinesis.region=us-east-1
aws.kinesis.consumer.group=default-group
aws.kinesis.consumer.stream=default-stream
aws.kinesis.consumer.max-records-per-call=1000
aws.kinesis.consumer.poll-interval-ms=1000
aws.kinesis.consumer.worker-threads=4
aws.kinesis.consumer.retry.max-attempts=3
aws.kinesis.consumer.retry.backoff-ms=1000
